[package]
name = "rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tensorflow = { version = "0.19.1", features = ["tensorflow_gpu"] }
scrap = "0.5"
quad-gamepad = "0.2.0-alpha"
image = "0.24.5"